// Build-time configuration
// This file is generated by meson during build

pub const APP_ID: &str = "io.github.tobagin.Sidestep";
pub const APP_NAME: &str = "Sidestep";
pub const VERSION: &str = "0.3.0";
pub const GETTEXT_PACKAGE: &str = "sidestep";
pub const LOCALEDIR: &str = "/usr/share/locale";
pub const PKGDATADIR: &str = "/usr/share/sidestep";
pub const SIDESTEP_DATA_DIR: &str = "/usr/share/sidestep";
